spring.application.name=email-writer-sb
#By this we can create the external Variable 
#gemini.api.url=https://generativelanguage.googleapis.com
gemini.api.url=${GEMINI_API_URL}
#gemini.api.key=AIzaSyDIvTcLSGcFRTrvLmuApRd21bOYbAeHqo4
gemini.api.key=${GEMINI_API_KEY}
server.port=8089
